tr_dual_steering:
  ros__parameters:
    wheel_diameter: 0.2
    publish_rate_hz: 50.0
    cmd_vel_topic: "/cmd_vel"
    traj_topic: "/joint_trajectory"

    module_names:  ["front", "rear"]
    steer_joints:  ["front_steer_joint", "rear_steer_joint"]
    drive_joints:  ["front_drive_joint", "rear_drive_joint"]
    module_x:      [0.46, -0.46]
    module_y:      [0.0,    0.0]
    caster_b_half: 0.3
    wheel_type: 'aligned'